drop table if exists ilga_income_worldbank;
create table ilga_income_worldbank
(
    id              int auto_increment primary key,
    iso3            varchar(3)  not null,
    year            varchar(4)  null,
    country         varchar(50) not null,
    income_category varchar(25) not null

) collate = utf8_unicode_ci;
create index ilga_income_worldbank_uk on ilga_income_worldbank (iso3,year);
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (1, 'AFG', 'Afghanistan', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (2, 'ALB', 'Albania', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (3, 'DZA', 'Algeria', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (4, 'ASM', 'American Samoa', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (5, 'AND', 'Andorra', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (6, 'AGO', 'Angola', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (7, 'ATG', 'Antigua and Barbuda', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (8, 'ARG', 'Argentina', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (9, 'ARM', 'Armenia', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (10, 'ABW', 'Aruba', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (11, 'AUS', 'Australia', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (12, 'AUT', 'Austria', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (13, 'AZE', 'Azerbaijan', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (14, 'BHS', 'Bahamas, The', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (15, 'BHR', 'Bahrain', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (16, 'BGD', 'Bangladesh', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (17, 'BRB', 'Barbados', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (18, 'BLR', 'Belarus', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (19, 'BEL', 'Belgium', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (20, 'BLZ', 'Belize', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (21, 'BEN', 'Benin', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (22, 'BMU', 'Bermuda', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (23, 'BTN', 'Bhutan', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (24, 'BOL', 'Bolivia', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (25, 'BIH', 'Bosnia and Herzegovina', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (26, 'BWA', 'Botswana', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (27, 'BRA', 'Brazil', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (28, 'VGB', 'British Virgin Islands', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (29, 'BRN', 'Brunei Darussalam', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (30, 'BGR', 'Bulgaria', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (31, 'BFA', 'Burkina Faso', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (32, 'BDI', 'Burundi', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (33, 'CPV', 'Cabo Verde', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (34, 'KHM', 'Cambodia', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (35, 'CMR', 'Cameroon', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (36, 'CAN', 'Canada', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (37, 'CYM', 'Cayman Islands', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (38, 'CAF', 'Central African Republic', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (39, 'TCD', 'Chad', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (40, 'CHI', 'Channel Islands', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (41, 'CHL', 'Chile', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (42, 'CHN', 'China', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (43, 'COL', 'Colombia', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (44, 'COM', 'Comoros', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (45, 'COD', 'Congo, Dem. Rep.', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (46, 'COG', 'Congo, Rep.', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (47, 'CRI', 'Costa Rica', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (48, 'CIV', 'Cte d''Ivoire', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (49, 'HRV', 'Croatia', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (50, 'CUB', 'Cuba', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (51, 'CUW', 'Curaao', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (52, 'CYP', 'Cyprus', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (53, 'CZE', 'Czech Republic', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (54, 'DNK', 'Denmark', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (55, 'DJI', 'Djibouti', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (56, 'DMA', 'Dominica', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (57, 'DOM', 'Dominican Republic', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (58, 'ECU', 'Ecuador', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (59, 'EGY', 'Egypt, Arab Rep.', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (60, 'SLV', 'El Salvador', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (61, 'GNQ', 'Equatorial Guinea', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (62, 'ERI', 'Eritrea', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (63, 'EST', 'Estonia', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (64, 'ETH', 'Ethiopia', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (65, 'FRO', 'Faroe Islands', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (66, 'FJI', 'Fiji', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (67, 'FIN', 'Finland', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (68, 'FRA', 'France', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (69, 'PYF', 'French Polynesia', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (70, 'GAB', 'Gabon', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (71, 'GMB', 'Gambia, The', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (72, 'GEO', 'Georgia', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (73, 'DEU', 'Germany', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (74, 'GHA', 'Ghana', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (75, 'GIB', 'Gibraltar', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (76, 'GRC', 'Greece', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (77, 'GRL', 'Greenland', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (78, 'GRD', 'Grenada', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (79, 'GUM', 'Guam', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (80, 'GTM', 'Guatemala', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (81, 'GIN', 'Guinea', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (82, 'GNB', 'Guinea-Bissau', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (83, 'GUY', 'Guyana', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (84, 'HTI', 'Haiti', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (85, 'HND', 'Honduras', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (86, 'HKG', 'Hong Kong SAR, China', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (87, 'HUN', 'Hungary', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (88, 'ISL', 'Iceland', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (89, 'IND', 'India', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (90, 'IDN', 'Indonesia', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (91, 'IRN', 'Iran, Islamic Rep.', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (92, 'IRQ', 'Iraq', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (93, 'IRL', 'Ireland', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (94, 'IMN', 'Isle of Man', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (95, 'ISR', 'Israel', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (96, 'ITA', 'Italy', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (97, 'JAM', 'Jamaica', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (98, 'JPN', 'Japan', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (99, 'JOR', 'Jordan', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (100, 'KAZ', 'Kazakhstan', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (101, 'KEN', 'Kenya', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (102, 'KIR', 'Kiribati', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (103, 'PRK', 'Korea, Dem. People''s Rep.', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (104, 'KOR', 'Korea, Rep.', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (105, 'XKX', 'Kosovo', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (106, 'KWT', 'Kuwait', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (107, 'KGZ', 'Kyrgyz Republic', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (108, 'LAO', 'Lao PDR', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (109, 'LVA', 'Latvia', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (110, 'LBN', 'Lebanon', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (111, 'LSO', 'Lesotho', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (112, 'LBR', 'Liberia', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (113, 'LBY', 'Libya', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (114, 'LIE', 'Liechtenstein', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (115, 'LTU', 'Lithuania', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (116, 'LUX', 'Luxembourg', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (117, 'MAC', 'Macao SAR, China', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (118, 'MKD', 'Macedonia, FYR', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (119, 'MDG', 'Madagascar', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (120, 'MWI', 'Malawi', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (121, 'MYS', 'Malaysia', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (122, 'MDV', 'Maldives', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (123, 'MLI', 'Mali', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (124, 'MLT', 'Malta', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (125, 'MHL', 'Marshall Islands', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (126, 'MRT', 'Mauritania', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (127, 'MUS', 'Mauritius', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (128, 'MEX', 'Mexico', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (129, 'FSM', 'Micronesia, Fed. Sts.', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (130, 'MDA', 'Moldova', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (131, 'MCO', 'Monaco', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (132, 'MNG', 'Mongolia', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (133, 'MNE', 'Montenegro', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (134, 'MAR', 'Morocco', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (135, 'MOZ', 'Mozambique', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (136, 'MMR', 'Myanmar', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (137, 'NAM', 'Namibia', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (138, 'NRU', 'Nauru', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (139, 'NPL', 'Nepal', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (140, 'NLD', 'Netherlands', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (141, 'NCL', 'New Caledonia', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (142, 'NZL', 'New Zealand', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (143, 'NIC', 'Nicaragua', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (144, 'NER', 'Niger', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (145, 'NGA', 'Nigeria', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (146, 'MNP', 'Northern Mariana Islands', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (147, 'NOR', 'Norway', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (148, 'OMN', 'Oman', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (149, 'PAK', 'Pakistan', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (150, 'PLW', 'Palau', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (151, 'PAN', 'Panama', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (152, 'PNG', 'Papua New Guinea', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (153, 'PRY', 'Paraguay', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (154, 'PER', 'Peru', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (155, 'PHL', 'Philippines', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (156, 'POL', 'Poland', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (157, 'PRT', 'Portugal', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (158, 'PRI', 'Puerto Rico', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (159, 'QAT', 'Qatar', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (160, 'ROU', 'Romania', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (161, 'RUS', 'Russian Federation', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (162, 'RWA', 'Rwanda', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (163, 'WSM', 'Samoa', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (164, 'SMR', 'San Marino', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (165, 'STP', 'So Tom and Principe', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (166, 'SAU', 'Saudi Arabia', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (167, 'SEN', 'Senegal', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (168, 'SRB', 'Serbia', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (169, 'SYC', 'Seychelles', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (170, 'SLE', 'Sierra Leone', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (171, 'SGP', 'Singapore', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (172, 'SXM', 'Sint Maarten (Dutch part)', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (173, 'SVK', 'Slovak Republic', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (174, 'SVN', 'Slovenia', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (175, 'SLB', 'Solomon Islands', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (176, 'SOM', 'Somalia', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (177, 'ZAF', 'South Africa', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (178, 'SSD', 'South Sudan', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (179, 'ESP', 'Spain', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (180, 'LKA', 'Sri Lanka', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (181, 'KNA', 'St. Kitts and Nevis', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (182, 'LCA', 'St. Lucia', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (183, 'MAF', 'St. Martin (French part)', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (184, 'VCT', 'St. Vincent and the Grenadines', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (185, 'SDN', 'Sudan', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (186, 'SUR', 'Suriname', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (187, 'SWZ', 'Swaziland', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (188, 'SWE', 'Sweden', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (189, 'CHE', 'Switzerland', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (190, 'SYR', 'Syrian Arab Republic', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (191, 'TWN', 'Taiwan, China', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (192, 'TJK', 'Tajikistan', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (193, 'TZA', 'Tanzania', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (194, 'THA', 'Thailand', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (195, 'TLS', 'Timor-Leste', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (196, 'TGO', 'Togo', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (197, 'TON', 'Tonga', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (198, 'TTO', 'Trinidad and Tobago', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (199, 'TUN', 'Tunisia', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (200, 'TUR', 'Turkey', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (201, 'TKM', 'Turkmenistan', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (202, 'TCA', 'Turks and Caicos Islands', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (203, 'TUV', 'Tuvalu', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (204, 'UGA', 'Uganda', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (205, 'UKR', 'Ukraine', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (206, 'ARE', 'United Arab Emirates', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (207, 'GBR', 'United Kingdom', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (208, 'USA', 'United States', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (209, 'URY', 'Uruguay', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (210, 'UZB', 'Uzbekistan', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (211, 'VUT', 'Vanuatu', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (212, 'VEN', 'Venezuela, RB', 'Upper middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (213, 'VNM', 'Vietnam', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (214, 'VIR', 'Virgin Islands (U.S.)', 'High income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (215, 'PSE', 'West Bank and Gaza', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (216, 'YEM', 'Yemen, Rep.', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (217, 'ZMB', 'Zambia', 'Lower middle income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (218, 'ZWE', 'Zimbabwe', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (219, 'BES', 'Bes Island', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (220, 'COK', 'Cook Islands', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (221, 'NIU', 'Niue', 'Low income', '2019');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (222, 'AFG', 'Afghanistan', 'Low income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (223, 'BEN', 'Benin', 'Low income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (224, 'BFA', 'Burkina Faso', 'Low income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (225, 'BDI', 'Burundi', 'Low income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (226, 'CAF', 'Central African Republic', 'Low income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (227, 'TCD', 'Chad', 'Low income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (228, 'COD', 'Congo, Dem. Rep.', 'Low income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (229, 'ERI', 'Eritrea', 'Low income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (230, 'ETH', 'Ethiopia', 'Low income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (231, 'GMB', 'Gambia, The', 'Low income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (232, 'GIN', 'Guinea', 'Low income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (233, 'GNB', 'Guinea-Bissau', 'Low income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (234, 'HTI', 'Haiti', 'Low income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (235, 'PRK', 'Korea, Dem. People''s Rep.', 'Low income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (236, 'LBR', 'Liberia', 'Low income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (237, 'MDG', 'Madagascar', 'Low income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (238, 'MWI', 'Malawi', 'Low income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (239, 'MLI', 'Mali', 'Low income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (240, 'MOZ', 'Mozambique', 'Low income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (241, 'NPL', 'Nepal', 'Low income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (242, 'NER', 'Niger', 'Low income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (243, 'RWA', 'Rwanda', 'Low income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (244, 'SLE', 'Sierra Leone', 'Low income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (245, 'SOM', 'Somalia', 'Low income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (246, 'SSD', 'South Sudan', 'Low income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (247, 'SYR', 'Syrian Arab Republic', 'Low income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (248, 'TJK', 'Tajikistan', 'Low income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (249, 'TZA', 'Tanzania', 'Low income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (250, 'TGO', 'Togo', 'Low income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (251, 'UGA', 'Uganda', 'Low income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (252, 'YEM', 'Yemen, Rep.', 'Low income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (253, 'AGO', 'Angola', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (254, 'BGD', 'Bangladesh', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (255, 'BTN', 'Bhutan', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (256, 'BOL', 'Bolivia', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (257, 'CPV', 'Cabo Verde', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (258, 'KHM', 'Cambodia', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (259, 'CMR', 'Cameroon', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (260, 'COM', 'Comoros', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (261, 'COG', 'Congo, Rep.', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (262, 'CIV', 'Côte d''Ivoire', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (263, 'DJI', 'Djibouti', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (264, 'EGY', 'Egypt, Arab Rep.', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (265, 'SLV', 'El Salvador', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (266, 'SWZ', 'Eswatini', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (267, 'GHA', 'Ghana', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (268, 'HND', 'Honduras', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (269, 'IND', 'India', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (270, 'IDN', 'Indonesia', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (271, 'KEN', 'Kenya', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (272, 'KIR', 'Kiribati', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (273, 'KGZ', 'Kyrgyz Republic', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (274, 'LAO', 'Lao PDR', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (275, 'LSO', 'Lesotho', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (276, 'MRT', 'Mauritania', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (277, 'FSM', 'Micronesia, Fed. Sts.', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (278, 'MDA', 'Moldova', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (279, 'MNG', 'Mongolia', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (280, 'MAR', 'Morocco', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (281, 'MMR', 'Myanmar', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (282, 'NIC', 'Nicaragua', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (283, 'NGA', 'Nigeria', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (284, 'PAK', 'Pakistan', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (285, 'PNG', 'Papua New Guinea', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (286, 'PHL', 'Philippines', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (287, 'SEN', 'Senegal', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (288, 'STP', 'São Tomé and Principe', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (289, 'SLB', 'Solomon Islands', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (290, 'SDN', 'Sudan', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (291, 'TLS', 'Timor-Leste', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (292, 'TUN', 'Tunisia', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (293, 'UKR', 'Ukraine', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (294, 'UZB', 'Uzbekistan', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (295, 'VUT', 'Vanuatu', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (296, 'VNM', 'Vietnam', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (297, 'PSE', 'West Bank and Gaza', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (298, 'ZMB', 'Zambia', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (299, 'ZWE', 'Zimbabwe', 'Lower middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (300, 'ALB', 'Albania', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (301, 'DZA', 'Algeria', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (302, 'ARM', 'Armenia', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (303, 'ASM', 'American Samoa', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (304, 'ARG', 'Argentina', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (305, 'AZE', 'Azerbaijan', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (306, 'BLR', 'Belarus', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (307, 'BLZ', 'Belize', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (308, 'BIH', 'Bosnia and Herzegovina', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (309, 'BWA', 'Botswana', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (310, 'BRA', 'Brazil', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (311, 'BGR', 'Bulgaria', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (312, 'CHN', 'China', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (313, 'COL', 'Colombia', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (314, 'CRI', 'Costa Rica', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (315, 'CUB', 'Cuba', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (316, 'DMA', 'Dominica', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (317, 'DOM', 'Dominican Republic', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (318, 'ECU', 'Ecuador', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (319, 'GNQ', 'Equatorial Guinea', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (320, 'GEO', 'Georgia', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (321, 'GTM', 'Guatemala', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (322, 'FJI', 'Fiji', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (323, 'GAB', 'Gabon', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (324, 'GRD', 'Grenada', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (325, 'GUY', 'Guyana', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (326, 'IRN', 'Iran, Islamic Rep.', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (327, 'IRQ', 'Iraq', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (328, 'JAM', 'Jamaica', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (329, 'JOR', 'Jordan', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (330, 'KAZ', 'Kazakhstan', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (331, 'XKX', 'Kosovo', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (332, 'LBN', 'Lebanon', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (333, 'LBY', 'Libya', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (334, 'MYS', 'Malaysia', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (335, 'MDV', 'Maldives', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (336, 'MHL', 'Marshall Islands', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (337, 'MUS', 'Mauritius', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (338, 'MEX', 'Mexico', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (339, 'MNE', 'Montenegro', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (340, 'NAM', 'Namibia', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (341, 'NRU', 'Nauru', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (342, 'MKD', 'North Macedonia', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (343, 'PRY', 'Paraguay', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (344, 'PER', 'Peru', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (345, 'ROU', 'Romania', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (346, 'RUS', 'Russian Federation', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (347, 'WSM', 'Samoa', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (348, 'SRB', 'Serbia', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (349, 'ZAF', 'South Africa', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (350, 'LKA', 'Sri Lanka', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (351, 'LCA', 'St. Lucia', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (352, 'VCT', 'St. Vincent and the Grenadines', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (353, 'SUR', 'Suriname', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (354, 'THA', 'Thailand', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (355, 'TON', 'Tonga', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (356, 'TUR', 'Turkey', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (357, 'TKM', 'Turkmenistan', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (358, 'TUV', 'Tuvalu', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (359, 'VEN', 'Venezuela, RB', 'Upper middle income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (360, 'AND', 'Andorra', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (361, 'ATG', 'Antigua and Barbuda', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (362, 'ABW', 'Aruba', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (363, 'AUS', 'Australia', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (364, 'AUT', 'Austria', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (365, 'BHS', 'Bahamas, The', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (366, 'BHR', 'Bahrain', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (367, 'BRB', 'Barbados', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (368, 'BEL', 'Belgium', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (369, 'BMU', 'Bermuda', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (370, 'VGB', 'British Virgin Islands', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (371, 'BRN', 'Brunei Darussalam', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (372, 'CAN', 'Canada', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (373, 'CYM', 'Cayman Islands', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (374, 'CHI', 'Channel Islands', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (375, 'CHL', 'Chile', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (376, 'HRV', 'Croatia', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (377, 'CUW', 'Curaçao', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (378, 'CYP', 'Cyprus', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (379, 'CZE', 'Czech Republic', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (380, 'DNK', 'Denmark', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (381, 'EST', 'Estonia', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (382, 'FRO', 'Faroe Islands', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (383, 'FIN', 'Finland', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (384, 'FRA', 'France', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (385, 'PYF', 'French Polynesia', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (386, 'DEU', 'Germany', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (387, 'GIB', 'Gibraltar', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (388, 'GRC', 'Greece', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (389, 'GRL', 'Greenland', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (390, 'GUM', 'Guam', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (391, 'HKG', 'Hong Kong SAR, China', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (392, 'HUN', 'Hungary', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (393, 'ISL', 'Iceland', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (394, 'IRL', 'Ireland', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (395, 'IMN', 'Isle of Man', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (396, 'ISR', 'Israel', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (397, 'ITA', 'Italy', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (398, 'JPN', 'Japan', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (399, 'KOR', 'Korea, Rep.', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (400, 'KWT', 'Kuwait', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (401, 'LVA', 'Latvia', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (402, 'LIE', 'Liechtenstein', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (403, 'LTU', 'Lithuania', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (404, 'LUX', 'Luxembourg', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (405, 'MAC', 'Macao SAR, China', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (406, 'MLT', 'Malta', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (407, 'MCO', 'Monaco', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (408, 'NLD', 'Netherlands', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (409, 'NCL', 'New Caledonia', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (410, 'NZL', 'New Zealand', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (411, 'MNP', 'Northern Mariana Islands', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (412, 'NOR', 'Norway', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (413, 'OMN', 'Oman', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (414, 'PLW', 'Palau', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (415, 'PAN', 'Panama', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (416, 'POL', 'Poland', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (417, 'PRT', 'Portugal', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (418, 'PRI', 'Puerto Rico', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (419, 'QAT', 'Qatar', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (420, 'SMR', 'San Marino', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (421, 'SAU', 'Saudi Arabia', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (422, 'SYC', 'Seychelles', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (423, 'SGP', 'Singapore', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (424, 'SXM', 'Sint Maarten (Dutch part)', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (425, 'SVK', 'Slovak Republic', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (426, 'SVN', 'Slovenia', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (427, 'ESP', 'Spain', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (428, 'KNA', 'St. Kitts and Nevis', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (429, 'MAF', 'St. Martin (French part)', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (430, 'SWE', 'Sweden', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (431, 'CHE', 'Switzerland', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (432, 'TWN', 'Taiwan, China', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (433, 'TTO', 'Trinidad and Tobago', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (434, 'TCA', 'Turks and Caicos Islands', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (435, 'ARE', 'United Arab Emirates', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (436, 'GBR', 'United Kingdom', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (437, 'USA', 'United States', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (438, 'URY', 'Uruguay', 'High income', '2020');
INSERT INTO ilga_income_worldbank (id, iso3, country, income_category, year) VALUES (439, 'VIR', 'Virgin Islands (U.S.)', 'High income', '2020');
