drop table if exists ilga_income_worldbank;
create table ilga_income_worldbank
(
    id              int auto_increment
        primary key,
    iso3            varchar(3)  not null,
    year            varchar(4)  null,
    country         varchar(50) not null,
    income_category varchar(25) not null
) collate = utf8_unicode_ci;
create unique index ilga_income_worldbank_uk on ilga_income_worldbank (iso3,year);

INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (1, 'AFG', '2019', 'Afghanistan', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (2, 'ALB', '2019', 'Albania', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (3, 'DZA', '2019', 'Algeria', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (4, 'ASM', '2019', 'American Samoa', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (5, 'AND', '2019', 'Andorra', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (6, 'AGO', '2019', 'Angola', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (7, 'ATG', '2019', 'Antigua and Barbuda', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (8, 'ARG', '2019', 'Argentina', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (9, 'ARM', '2019', 'Armenia', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (10, 'ABW', '2019', 'Aruba', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (11, 'AUS', '2019', 'Australia', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (12, 'AUT', '2019', 'Austria', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (13, 'AZE', '2019', 'Azerbaijan', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (14, 'BHS', '2019', 'Bahamas, The', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (15, 'BHR', '2019', 'Bahrain', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (16, 'BGD', '2019', 'Bangladesh', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (17, 'BRB', '2019', 'Barbados', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (18, 'BLR', '2019', 'Belarus', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (19, 'BEL', '2019', 'Belgium', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (20, 'BLZ', '2019', 'Belize', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (21, 'BEN', '2019', 'Benin', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (22, 'BMU', '2019', 'Bermuda', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (23, 'BTN', '2019', 'Bhutan', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (24, 'BOL', '2019', 'Bolivia', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (25, 'BIH', '2019', 'Bosnia and Herzegovina', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (26, 'BWA', '2019', 'Botswana', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (27, 'BRA', '2019', 'Brazil', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (28, 'VGB', '2019', 'British Virgin Islands', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (29, 'BRN', '2019', 'Brunei Darussalam', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (30, 'BGR', '2019', 'Bulgaria', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (31, 'BFA', '2019', 'Burkina Faso', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (32, 'BDI', '2019', 'Burundi', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (33, 'CPV', '2019', 'Cabo Verde', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (34, 'KHM', '2019', 'Cambodia', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (35, 'CMR', '2019', 'Cameroon', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (36, 'CAN', '2019', 'Canada', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (37, 'CYM', '2019', 'Cayman Islands', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (38, 'CAF', '2019', 'Central African Republic', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (39, 'TCD', '2019', 'Chad', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (40, 'CHI', '2019', 'Channel Islands', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (41, 'CHL', '2019', 'Chile', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (42, 'CHN', '2019', 'China', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (43, 'COL', '2019', 'Colombia', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (44, 'COM', '2019', 'Comoros', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (45, 'COD', '2019', 'Congo, Dem. Rep.', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (46, 'COG', '2019', 'Congo, Rep.', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (47, 'CRI', '2019', 'Costa Rica', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (48, 'CIV', '2019', 'Cte d''Ivoire', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (49, 'HRV', '2019', 'Croatia', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (50, 'CUB', '2019', 'Cuba', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (51, 'CUW', '2019', 'Curaao', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (52, 'CYP', '2019', 'Cyprus', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (53, 'CZE', '2019', 'Czech Republic', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (54, 'DNK', '2019', 'Denmark', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (55, 'DJI', '2019', 'Djibouti', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (56, 'DMA', '2019', 'Dominica', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (57, 'DOM', '2019', 'Dominican Republic', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (58, 'ECU', '2019', 'Ecuador', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (59, 'EGY', '2019', 'Egypt, Arab Rep.', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (60, 'SLV', '2019', 'El Salvador', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (61, 'GNQ', '2019', 'Equatorial Guinea', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (62, 'ERI', '2019', 'Eritrea', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (63, 'EST', '2019', 'Estonia', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (64, 'ETH', '2019', 'Ethiopia', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (65, 'FRO', '2019', 'Faroe Islands', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (66, 'FJI', '2019', 'Fiji', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (67, 'FIN', '2019', 'Finland', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (68, 'FRA', '2019', 'France', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (69, 'PYF', '2019', 'French Polynesia', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (70, 'GAB', '2019', 'Gabon', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (71, 'GMB', '2019', 'Gambia, The', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (72, 'GEO', '2019', 'Georgia', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (73, 'DEU', '2019', 'Germany', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (74, 'GHA', '2019', 'Ghana', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (75, 'GIB', '2019', 'Gibraltar', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (76, 'GRC', '2019', 'Greece', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (77, 'GRL', '2019', 'Greenland', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (78, 'GRD', '2019', 'Grenada', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (79, 'GUM', '2019', 'Guam', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (80, 'GTM', '2019', 'Guatemala', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (81, 'GIN', '2019', 'Guinea', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (82, 'GNB', '2019', 'Guinea-Bissau', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (83, 'GUY', '2019', 'Guyana', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (84, 'HTI', '2019', 'Haiti', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (85, 'HND', '2019', 'Honduras', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (86, 'HKG', '2019', 'Hong Kong SAR, China', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (87, 'HUN', '2019', 'Hungary', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (88, 'ISL', '2019', 'Iceland', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (89, 'IND', '2019', 'India', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (90, 'IDN', '2019', 'Indonesia', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (91, 'IRN', '2019', 'Iran, Islamic Rep.', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (92, 'IRQ', '2019', 'Iraq', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (93, 'IRL', '2019', 'Ireland', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (94, 'IMN', '2019', 'Isle of Man', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (95, 'ISR', '2019', 'Israel', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (96, 'ITA', '2019', 'Italy', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (97, 'JAM', '2019', 'Jamaica', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (98, 'JPN', '2019', 'Japan', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (99, 'JOR', '2019', 'Jordan', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (100, 'KAZ', '2019', 'Kazakhstan', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (101, 'KEN', '2019', 'Kenya', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (102, 'KIR', '2019', 'Kiribati', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (103, 'PRK', '2019', 'Korea, Dem. People''s Rep.', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (104, 'KOR', '2019', 'Korea, Rep.', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (105, 'XKX', '2019', 'Kosovo', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (106, 'KWT', '2019', 'Kuwait', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (107, 'KGZ', '2019', 'Kyrgyz Republic', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (108, 'LAO', '2019', 'Lao PDR', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (109, 'LVA', '2019', 'Latvia', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (110, 'LBN', '2019', 'Lebanon', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (111, 'LSO', '2019', 'Lesotho', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (112, 'LBR', '2019', 'Liberia', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (113, 'LBY', '2019', 'Libya', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (114, 'LIE', '2019', 'Liechtenstein', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (115, 'LTU', '2019', 'Lithuania', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (116, 'LUX', '2019', 'Luxembourg', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (117, 'MAC', '2019', 'Macao SAR, China', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (118, 'MKD', '2019', 'Macedonia, FYR', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (119, 'MDG', '2019', 'Madagascar', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (120, 'MWI', '2019', 'Malawi', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (121, 'MYS', '2019', 'Malaysia', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (122, 'MDV', '2019', 'Maldives', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (123, 'MLI', '2019', 'Mali', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (124, 'MLT', '2019', 'Malta', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (125, 'MHL', '2019', 'Marshall Islands', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (126, 'MRT', '2019', 'Mauritania', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (127, 'MUS', '2019', 'Mauritius', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (128, 'MEX', '2019', 'Mexico', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (129, 'FSM', '2019', 'Micronesia, Fed. Sts.', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (130, 'MDA', '2019', 'Moldova', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (131, 'MCO', '2019', 'Monaco', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (132, 'MNG', '2019', 'Mongolia', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (133, 'MNE', '2019', 'Montenegro', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (134, 'MAR', '2019', 'Morocco', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (135, 'MOZ', '2019', 'Mozambique', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (136, 'MMR', '2019', 'Myanmar', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (137, 'NAM', '2019', 'Namibia', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (138, 'NRU', '2019', 'Nauru', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (139, 'NPL', '2019', 'Nepal', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (140, 'NLD', '2019', 'Netherlands', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (141, 'NCL', '2019', 'New Caledonia', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (142, 'NZL', '2019', 'New Zealand', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (143, 'NIC', '2019', 'Nicaragua', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (144, 'NER', '2019', 'Niger', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (145, 'NGA', '2019', 'Nigeria', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (146, 'MNP', '2019', 'Northern Mariana Islands', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (147, 'NOR', '2019', 'Norway', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (148, 'OMN', '2019', 'Oman', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (149, 'PAK', '2019', 'Pakistan', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (150, 'PLW', '2019', 'Palau', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (151, 'PAN', '2019', 'Panama', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (152, 'PNG', '2019', 'Papua New Guinea', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (153, 'PRY', '2019', 'Paraguay', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (154, 'PER', '2019', 'Peru', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (155, 'PHL', '2019', 'Philippines', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (156, 'POL', '2019', 'Poland', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (157, 'PRT', '2019', 'Portugal', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (158, 'PRI', '2019', 'Puerto Rico', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (159, 'QAT', '2019', 'Qatar', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (160, 'ROU', '2019', 'Romania', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (161, 'RUS', '2019', 'Russian Federation', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (162, 'RWA', '2019', 'Rwanda', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (163, 'WSM', '2019', 'Samoa', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (164, 'SMR', '2019', 'San Marino', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (165, 'STP', '2019', 'So Tom and Principe', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (166, 'SAU', '2019', 'Saudi Arabia', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (167, 'SEN', '2019', 'Senegal', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (168, 'SRB', '2019', 'Serbia', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (169, 'SYC', '2019', 'Seychelles', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (170, 'SLE', '2019', 'Sierra Leone', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (171, 'SGP', '2019', 'Singapore', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (172, 'SXM', '2019', 'Sint Maarten (Dutch part)', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (173, 'SVK', '2019', 'Slovak Republic', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (174, 'SVN', '2019', 'Slovenia', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (175, 'SLB', '2019', 'Solomon Islands', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (176, 'SOM', '2019', 'Somalia', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (177, 'ZAF', '2019', 'South Africa', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (178, 'SSD', '2019', 'South Sudan', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (179, 'ESP', '2019', 'Spain', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (180, 'LKA', '2019', 'Sri Lanka', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (181, 'KNA', '2019', 'St. Kitts and Nevis', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (182, 'LCA', '2019', 'St. Lucia', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (183, 'MAF', '2019', 'St. Martin (French part)', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (184, 'VCT', '2019', 'St. Vincent and the Grenadines', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (185, 'SDN', '2019', 'Sudan', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (186, 'SUR', '2019', 'Suriname', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (187, 'SWZ', '2019', 'Swaziland', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (188, 'SWE', '2019', 'Sweden', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (189, 'CHE', '2019', 'Switzerland', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (190, 'SYR', '2019', 'Syrian Arab Republic', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (191, 'TWN', '2019', 'Taiwan, China', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (192, 'TJK', '2019', 'Tajikistan', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (193, 'TZA', '2019', 'Tanzania', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (194, 'THA', '2019', 'Thailand', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (195, 'TLS', '2019', 'Timor-Leste', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (196, 'TGO', '2019', 'Togo', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (197, 'TON', '2019', 'Tonga', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (198, 'TTO', '2019', 'Trinidad and Tobago', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (199, 'TUN', '2019', 'Tunisia', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (200, 'TUR', '2019', 'Turkey', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (201, 'TKM', '2019', 'Turkmenistan', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (202, 'TCA', '2019', 'Turks and Caicos Islands', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (203, 'TUV', '2019', 'Tuvalu', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (204, 'UGA', '2019', 'Uganda', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (205, 'UKR', '2019', 'Ukraine', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (206, 'ARE', '2019', 'United Arab Emirates', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (207, 'GBR', '2019', 'United Kingdom', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (208, 'USA', '2019', 'United States', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (209, 'URY', '2019', 'Uruguay', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (210, 'UZB', '2019', 'Uzbekistan', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (211, 'VUT', '2019', 'Vanuatu', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (212, 'VEN', '2019', 'Venezuela, RB', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (213, 'VNM', '2019', 'Vietnam', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (214, 'VIR', '2019', 'Virgin Islands (U.S.)', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (215, 'PSE', '2019', 'West Bank and Gaza', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (216, 'YEM', '2019', 'Yemen, Rep.', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (217, 'ZMB', '2019', 'Zambia', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (218, 'ZWE', '2019', 'Zimbabwe', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (219, 'BES', '2019', 'Bes Island', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (220, 'COK', '2019', 'Cook Islands', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (221, 'NIU', '2019', 'Niue', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (222, 'AFG', '2020', 'Afghanistan', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (223, 'BEN', '2020', 'Benin', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (224, 'BFA', '2020', 'Burkina Faso', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (225, 'BDI', '2020', 'Burundi', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (226, 'CAF', '2020', 'Central African Republic', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (227, 'TCD', '2020', 'Chad', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (228, 'COD', '2020', 'Congo, Dem. Rep.', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (229, 'ERI', '2020', 'Eritrea', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (230, 'ETH', '2020', 'Ethiopia', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (231, 'GMB', '2020', 'Gambia, The', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (232, 'GIN', '2020', 'Guinea', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (233, 'GNB', '2020', 'Guinea-Bissau', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (234, 'HTI', '2020', 'Haiti', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (235, 'PRK', '2020', 'Korea, Dem. People''s Rep.', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (236, 'LBR', '2020', 'Liberia', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (237, 'MDG', '2020', 'Madagascar', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (238, 'MWI', '2020', 'Malawi', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (239, 'MLI', '2020', 'Mali', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (240, 'MOZ', '2020', 'Mozambique', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (241, 'NPL', '2020', 'Nepal', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (242, 'NER', '2020', 'Niger', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (243, 'RWA', '2020', 'Rwanda', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (244, 'SLE', '2020', 'Sierra Leone', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (245, 'SOM', '2020', 'Somalia', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (246, 'SSD', '2020', 'South Sudan', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (247, 'SYR', '2020', 'Syrian Arab Republic', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (248, 'TJK', '2020', 'Tajikistan', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (249, 'TZA', '2020', 'Tanzania', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (250, 'TGO', '2020', 'Togo', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (251, 'UGA', '2020', 'Uganda', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (252, 'YEM', '2020', 'Yemen, Rep.', 'Low income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (253, 'AGO', '2020', 'Angola', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (254, 'BGD', '2020', 'Bangladesh', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (255, 'BTN', '2020', 'Bhutan', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (256, 'BOL', '2020', 'Bolivia', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (257, 'CPV', '2020', 'Cabo Verde', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (258, 'KHM', '2020', 'Cambodia', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (259, 'CMR', '2020', 'Cameroon', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (260, 'COM', '2020', 'Comoros', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (261, 'COG', '2020', 'Congo, Rep.', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (262, 'CIV', '2020', 'Côte d''Ivoire', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (263, 'DJI', '2020', 'Djibouti', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (264, 'EGY', '2020', 'Egypt, Arab Rep.', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (265, 'SLV', '2020', 'El Salvador', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (266, 'SWZ', '2020', 'Eswatini', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (267, 'GHA', '2020', 'Ghana', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (268, 'HND', '2020', 'Honduras', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (269, 'IND', '2020', 'India', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (270, 'IDN', '2020', 'Indonesia', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (271, 'KEN', '2020', 'Kenya', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (272, 'KIR', '2020', 'Kiribati', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (273, 'KGZ', '2020', 'Kyrgyz Republic', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (274, 'LAO', '2020', 'Lao PDR', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (275, 'LSO', '2020', 'Lesotho', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (276, 'MRT', '2020', 'Mauritania', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (277, 'FSM', '2020', 'Micronesia, Fed. Sts.', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (278, 'MDA', '2020', 'Moldova', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (279, 'MNG', '2020', 'Mongolia', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (280, 'MAR', '2020', 'Morocco', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (281, 'MMR', '2020', 'Myanmar', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (282, 'NIC', '2020', 'Nicaragua', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (283, 'NGA', '2020', 'Nigeria', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (284, 'PAK', '2020', 'Pakistan', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (285, 'PNG', '2020', 'Papua New Guinea', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (286, 'PHL', '2020', 'Philippines', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (287, 'SEN', '2020', 'Senegal', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (288, 'STP', '2020', 'São Tomé and Principe', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (289, 'SLB', '2020', 'Solomon Islands', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (290, 'SDN', '2020', 'Sudan', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (291, 'TLS', '2020', 'Timor-Leste', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (292, 'TUN', '2020', 'Tunisia', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (293, 'UKR', '2020', 'Ukraine', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (294, 'UZB', '2020', 'Uzbekistan', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (295, 'VUT', '2020', 'Vanuatu', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (296, 'VNM', '2020', 'Vietnam', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (297, 'PSE', '2020', 'West Bank and Gaza', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (298, 'ZMB', '2020', 'Zambia', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (299, 'ZWE', '2020', 'Zimbabwe', 'Lower middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (300, 'ALB', '2020', 'Albania', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (301, 'DZA', '2020', 'Algeria', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (302, 'ARM', '2020', 'Armenia', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (303, 'ASM', '2020', 'American Samoa', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (304, 'ARG', '2020', 'Argentina', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (305, 'AZE', '2020', 'Azerbaijan', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (306, 'BLR', '2020', 'Belarus', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (307, 'BLZ', '2020', 'Belize', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (308, 'BIH', '2020', 'Bosnia and Herzegovina', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (309, 'BWA', '2020', 'Botswana', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (310, 'BRA', '2020', 'Brazil', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (311, 'BGR', '2020', 'Bulgaria', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (312, 'CHN', '2020', 'China', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (313, 'COL', '2020', 'Colombia', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (314, 'CRI', '2020', 'Costa Rica', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (315, 'CUB', '2020', 'Cuba', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (316, 'DMA', '2020', 'Dominica', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (317, 'DOM', '2020', 'Dominican Republic', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (318, 'ECU', '2020', 'Ecuador', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (319, 'GNQ', '2020', 'Equatorial Guinea', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (320, 'GEO', '2020', 'Georgia', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (321, 'GTM', '2020', 'Guatemala', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (322, 'FJI', '2020', 'Fiji', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (323, 'GAB', '2020', 'Gabon', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (324, 'GRD', '2020', 'Grenada', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (325, 'GUY', '2020', 'Guyana', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (326, 'IRN', '2020', 'Iran, Islamic Rep.', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (327, 'IRQ', '2020', 'Iraq', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (328, 'JAM', '2020', 'Jamaica', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (329, 'JOR', '2020', 'Jordan', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (330, 'KAZ', '2020', 'Kazakhstan', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (331, 'XKX', '2020', 'Kosovo', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (332, 'LBN', '2020', 'Lebanon', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (333, 'LBY', '2020', 'Libya', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (334, 'MYS', '2020', 'Malaysia', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (335, 'MDV', '2020', 'Maldives', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (336, 'MHL', '2020', 'Marshall Islands', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (337, 'MUS', '2020', 'Mauritius', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (338, 'MEX', '2020', 'Mexico', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (339, 'MNE', '2020', 'Montenegro', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (340, 'NAM', '2020', 'Namibia', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (341, 'NRU', '2020', 'Nauru', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (342, 'MKD', '2020', 'North Macedonia', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (343, 'PRY', '2020', 'Paraguay', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (344, 'PER', '2020', 'Peru', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (345, 'ROU', '2020', 'Romania', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (346, 'RUS', '2020', 'Russian Federation', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (347, 'WSM', '2020', 'Samoa', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (348, 'SRB', '2020', 'Serbia', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (349, 'ZAF', '2020', 'South Africa', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (350, 'LKA', '2020', 'Sri Lanka', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (351, 'LCA', '2020', 'St. Lucia', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (352, 'VCT', '2020', 'St. Vincent and the Grenadines', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (353, 'SUR', '2020', 'Suriname', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (354, 'THA', '2020', 'Thailand', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (355, 'TON', '2020', 'Tonga', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (356, 'TUR', '2020', 'Turkey', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (357, 'TKM', '2020', 'Turkmenistan', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (358, 'TUV', '2020', 'Tuvalu', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (359, 'VEN', '2020', 'Venezuela, RB', 'Upper middle income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (360, 'AND', '2020', 'Andorra', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (361, 'ATG', '2020', 'Antigua and Barbuda', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (362, 'ABW', '2020', 'Aruba', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (363, 'AUS', '2020', 'Australia', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (364, 'AUT', '2020', 'Austria', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (365, 'BHS', '2020', 'Bahamas, The', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (366, 'BHR', '2020', 'Bahrain', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (367, 'BRB', '2020', 'Barbados', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (368, 'BEL', '2020', 'Belgium', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (369, 'BMU', '2020', 'Bermuda', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (370, 'VGB', '2020', 'British Virgin Islands', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (371, 'BRN', '2020', 'Brunei Darussalam', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (372, 'CAN', '2020', 'Canada', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (373, 'CYM', '2020', 'Cayman Islands', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (374, 'CHI', '2020', 'Channel Islands', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (375, 'CHL', '2020', 'Chile', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (376, 'HRV', '2020', 'Croatia', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (377, 'CUW', '2020', 'Curaçao', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (378, 'CYP', '2020', 'Cyprus', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (379, 'CZE', '2020', 'Czech Republic', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (380, 'DNK', '2020', 'Denmark', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (381, 'EST', '2020', 'Estonia', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (382, 'FRO', '2020', 'Faroe Islands', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (383, 'FIN', '2020', 'Finland', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (384, 'FRA', '2020', 'France', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (385, 'PYF', '2020', 'French Polynesia', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (386, 'DEU', '2020', 'Germany', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (387, 'GIB', '2020', 'Gibraltar', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (388, 'GRC', '2020', 'Greece', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (389, 'GRL', '2020', 'Greenland', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (390, 'GUM', '2020', 'Guam', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (391, 'HKG', '2020', 'Hong Kong SAR, China', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (392, 'HUN', '2020', 'Hungary', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (393, 'ISL', '2020', 'Iceland', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (394, 'IRL', '2020', 'Ireland', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (395, 'IMN', '2020', 'Isle of Man', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (396, 'ISR', '2020', 'Israel', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (397, 'ITA', '2020', 'Italy', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (398, 'JPN', '2020', 'Japan', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (399, 'KOR', '2020', 'Korea, Rep.', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (400, 'KWT', '2020', 'Kuwait', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (401, 'LVA', '2020', 'Latvia', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (402, 'LIE', '2020', 'Liechtenstein', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (403, 'LTU', '2020', 'Lithuania', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (404, 'LUX', '2020', 'Luxembourg', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (405, 'MAC', '2020', 'Macao SAR, China', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (406, 'MLT', '2020', 'Malta', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (407, 'MCO', '2020', 'Monaco', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (408, 'NLD', '2020', 'Netherlands', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (409, 'NCL', '2020', 'New Caledonia', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (410, 'NZL', '2020', 'New Zealand', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (411, 'MNP', '2020', 'Northern Mariana Islands', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (412, 'NOR', '2020', 'Norway', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (413, 'OMN', '2020', 'Oman', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (414, 'PLW', '2020', 'Palau', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (415, 'PAN', '2020', 'Panama', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (416, 'POL', '2020', 'Poland', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (417, 'PRT', '2020', 'Portugal', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (418, 'PRI', '2020', 'Puerto Rico', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (419, 'QAT', '2020', 'Qatar', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (420, 'SMR', '2020', 'San Marino', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (421, 'SAU', '2020', 'Saudi Arabia', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (422, 'SYC', '2020', 'Seychelles', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (423, 'SGP', '2020', 'Singapore', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (424, 'SXM', '2020', 'Sint Maarten (Dutch part)', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (425, 'SVK', '2020', 'Slovak Republic', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (426, 'SVN', '2020', 'Slovenia', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (427, 'ESP', '2020', 'Spain', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (428, 'KNA', '2020', 'St. Kitts and Nevis', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (429, 'MAF', '2020', 'St. Martin (French part)', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (430, 'SWE', '2020', 'Sweden', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (431, 'CHE', '2020', 'Switzerland', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (432, 'TWN', '2020', 'Taiwan, China', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (433, 'TTO', '2020', 'Trinidad and Tobago', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (434, 'TCA', '2020', 'Turks and Caicos Islands', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (435, 'ARE', '2020', 'United Arab Emirates', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (436, 'GBR', '2020', 'United Kingdom', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (437, 'USA', '2020', 'United States', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (438, 'URY', '2020', 'Uruguay', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (439, 'VIR', '2020', 'Virgin Islands (U.S.)', 'High income');
INSERT INTO ilga_income_worldbank (id, iso3, year, country, income_category) VALUES (440, 'JEY', '2020', 'Jersey', 'High income');
