/*
 * @author Klaas Eikelboom  <klaas.eikelboom@civicoop.org>
 * @date 29-Jan-2020
 * @license  AGPL-3.0
 */
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'ABW', 'Aruba', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'AND', 'Andorra', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'ARE', 'United Arab Emirates', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'ATG', 'Antigua and Barbuda', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'AUS', 'Australia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'AUT', 'Austria', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'BEL', 'Belgium', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'BHR', 'Bahrain', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'BHS', 'Bahamas, The', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'BMU', 'Bermuda', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'BRB', 'Barbados', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'BRN', 'Brunei Darussalam', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'CAN', 'Canada', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'CHE', 'Switzerland', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'CHI', 'Channel Islands', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'CHL', 'Chile', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'CUW', 'Curacao', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'CYM', 'Cayman Islands', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'CYP', 'Cyprus', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'CZE', 'Czech Republic', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'DEU', 'Germany', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'DNK', 'Denmark', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'ESP', 'Spain', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'EST', 'Estonia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'FIN', 'Finland', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'FRA', 'France', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'FRO', 'Faroe Islands', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'GBR', 'United Kingdom', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'GIB', 'Gibraltar', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'GRC', 'Greece', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'GRL', 'Greenland', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'GUM', 'Guam', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'HKG', 'Hong Kong SAR, China', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'HRV', 'Croatia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'HUN', 'Hungary', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'IMN', 'Isle of Man', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'IRL', 'Ireland', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'ISL', 'Iceland', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'ISR', 'Israel', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'ITA', 'Italy', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'JPN', 'Japan', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'KNA', 'St. Kitts and Nevis', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'KOR', 'Korea, Rep.', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'KWT', 'Kuwait', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'LIE', 'Liechtenstein', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'LTU', 'Lithuania', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'LUX', 'Luxembourg', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'LVA', 'Latvia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'MAC', 'Macao SAR, China', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'MAF', 'St. Martin (French part)', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'MCO', 'Monaco', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'MLT', 'Malta', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'MNP', 'Northern Mariana Islands', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'MUS', 'Mauritius', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'NCL', 'New Caledonia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'NLD', 'Netherlands', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'NOR', 'Norway', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'NRU', 'Nauru', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'NZL', 'New Zealand', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'OMN', 'Oman', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'PAN', 'Panama', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'PLW', 'Palau', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'POL', 'Poland', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'PRI', 'Puerto Rico', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'PRT', 'Portugal', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'PYF', 'French Polynesia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'QAT', 'Qatar', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'ROU', 'Romania', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'SAU', 'Saudi Arabia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'SGP', 'Singapore', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'SMR', 'San Marino', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'SVK', 'Slovak Republic', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'SVN', 'Slovenia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'SWE', 'Sweden', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'SXM', 'Sint Maarten (Dutch part)', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'SYC', 'Seychelles', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'TCA', 'Turks and Caicos Islands', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'TTO', 'Trinidad and Tobago', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'TWN', 'Taiwan, China', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'URY', 'Uruguay', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'USA', 'United States', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'VGB', 'British Virgin Islands', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('HIC', 'VIR', 'Virgin Islands (U.S.)', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LIC', 'AFG', 'Afghanistan', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LIC', 'BDI', 'Burundi', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LIC', 'BFA', 'Burkina Faso', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LIC', 'CAF', 'Central African Republic', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LIC', 'COD', 'Congo, Dem. Rep.', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LIC', 'ERI', 'Eritrea', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LIC', 'ETH', 'Ethiopia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LIC', 'GIN', 'Guinea', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LIC', 'GMB', 'Gambia, The', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LIC', 'GNB', 'Guinea-Bissau', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LIC', 'HTI', 'Haiti', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LIC', 'LBR', 'Liberia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LIC', 'MDG', 'Madagascar', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LIC', 'MLI', 'Mali', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LIC', 'MOZ', 'Mozambique', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LIC', 'MWI', 'Malawi', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LIC', 'NER', 'Niger', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LIC', 'PRK', 'Korea, Dem. People''s Rep.', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LIC', 'RWA', 'Rwanda', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LIC', 'SDN', 'Sudan', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LIC', 'SLE', 'Sierra Leone', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LIC', 'SOM', 'Somalia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LIC', 'SSD', 'South Sudan', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LIC', 'SYR', 'Syrian Arab Republic', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LIC', 'TCD', 'Chad', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LIC', 'TGO', 'Togo', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LIC', 'TJK', 'Tajikistan', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LIC', 'UGA', 'Uganda', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LIC', 'YEM', 'Yemen, Rep.', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'AGO', 'Angola', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'BEN', 'Benin', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'BGD', 'Bangladesh', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'BOL', 'Bolivia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'BTN', 'Bhutan', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'CIV', 'Cote d''Ivoire', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'CMR', 'Cameroon', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'COG', 'Congo, Rep.', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'COM', 'Comoros', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'CPV', 'Cabo Verde', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'DJI', 'Djibouti', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'DZA', 'Algeria', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'EGY', 'Egypt, Arab Rep.', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'FSM', 'Micronesia, Fed. Sts.', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'GHA', 'Ghana', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'HND', 'Honduras', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'IND', 'India', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'KEN', 'Kenya', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'KGZ', 'Kyrgyz Republic', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'KHM', 'Cambodia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'KIR', 'Kiribati', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'LAO', 'Lao PDR', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'LKA', 'Sri Lanka', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'LSO', 'Lesotho', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'MAR', 'Morocco', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'MDA', 'Moldova', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'MMR', 'Myanmar', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'MNG', 'Mongolia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'MRT', 'Mauritania', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'NGA', 'Nigeria', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'NIC', 'Nicaragua', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'NPL', 'Nepal', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'PAK', 'Pakistan', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'PHL', 'Philippines', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'PNG', 'Papua New Guinea', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'PSE', 'West Bank and Gaza', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'SEN', 'Senegal', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'SLB', 'Solomon Islands', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'SLV', 'El Salvador', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'STP', 'Sao Tome and Principe', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'SWZ', 'Eswatini', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'TLS', 'Timor-Leste', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'TUN', 'Tunisia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'TZA', 'Tanzania', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'UKR', 'Ukraine', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'UZB', 'Uzbekistan', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'VNM', 'Vietnam', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'VUT', 'Vanuatu', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'ZMB', 'Zambia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMC', 'ZWE', 'Zimbabwe', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'AFG', 'Afghanistan', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'AGO', 'Angola', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'ALB', 'Albania', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'ARG', 'Argentina', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'ARM', 'Armenia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'ASM', 'American Samoa', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'AZE', 'Azerbaijan', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'BDI', 'Burundi', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'BEN', 'Benin', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'BFA', 'Burkina Faso', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'BGD', 'Bangladesh', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'BGR', 'Bulgaria', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'BIH', 'Bosnia and Herzegovina', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'BLR', 'Belarus', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'BLZ', 'Belize', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'BOL', 'Bolivia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'BRA', 'Brazil', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'BTN', 'Bhutan', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'BWA', 'Botswana', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'CAF', 'Central African Republic', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'CHN', 'China', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'CIV', 'Cote d''Ivoire', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'CMR', 'Cameroon', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'COD', 'Congo, Dem. Rep.', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'COG', 'Congo, Rep.', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'COL', 'Colombia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'COM', 'Comoros', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'CPV', 'Cabo Verde', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'CRI', 'Costa Rica', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'CUB', 'Cuba', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'DJI', 'Djibouti', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'DMA', 'Dominica', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'DOM', 'Dominican Republic', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'DZA', 'Algeria', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'ECU', 'Ecuador', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'EGY', 'Egypt, Arab Rep.', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'ERI', 'Eritrea', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'ETH', 'Ethiopia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'FJI', 'Fiji', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'FSM', 'Micronesia, Fed. Sts.', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'GAB', 'Gabon', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'GEO', 'Georgia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'GHA', 'Ghana', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'GIN', 'Guinea', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'GMB', 'Gambia, The', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'GNB', 'Guinea-Bissau', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'GNQ', 'Equatorial Guinea', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'GRD', 'Grenada', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'GTM', 'Guatemala', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'GUY', 'Guyana', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'HND', 'Honduras', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'HTI', 'Haiti', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'IDN', 'Indonesia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'IND', 'India', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'IRN', 'Iran, Islamic Rep.', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'IRQ', 'Iraq', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'JAM', 'Jamaica', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'JOR', 'Jordan', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'KAZ', 'Kazakhstan', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'KEN', 'Kenya', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'KGZ', 'Kyrgyz Republic', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'KHM', 'Cambodia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'KIR', 'Kiribati', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'LAO', 'Lao PDR', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'LBN', 'Lebanon', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'LBR', 'Liberia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'LBY', 'Libya', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'LCA', 'St. Lucia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'LKA', 'Sri Lanka', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'LSO', 'Lesotho', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'MAR', 'Morocco', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'MDA', 'Moldova', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'MDG', 'Madagascar', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'MDV', 'Maldives', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'MEX', 'Mexico', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'MHL', 'Marshall Islands', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'MKD', 'North Macedonia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'MLI', 'Mali', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'MMR', 'Myanmar', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'MNE', 'Montenegro', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'MNG', 'Mongolia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'MOZ', 'Mozambique', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'MRT', 'Mauritania', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'MWI', 'Malawi', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'MYS', 'Malaysia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'NAM', 'Namibia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'NER', 'Niger', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'NGA', 'Nigeria', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'NIC', 'Nicaragua', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'NPL', 'Nepal', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'PAK', 'Pakistan', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'PER', 'Peru', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'PHL', 'Philippines', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'PNG', 'Papua New Guinea', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'PRK', 'Korea, Dem. People''s Rep.', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'PRY', 'Paraguay', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'PSE', 'West Bank and Gaza', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'RUS', 'Russian Federation', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'RWA', 'Rwanda', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'SDN', 'Sudan', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'SEN', 'Senegal', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'SLB', 'Solomon Islands', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'SLE', 'Sierra Leone', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'SLV', 'El Salvador', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'SOM', 'Somalia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'SRB', 'Serbia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'SSD', 'South Sudan', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'STP', 'Sao Tome and Principe', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'SUR', 'Suriname', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'SWZ', 'Eswatini', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'SYR', 'Syrian Arab Republic', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'TCD', 'Chad', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'TGO', 'Togo', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'THA', 'Thailand', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'TJK', 'Tajikistan', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'TKM', 'Turkmenistan', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'TLS', 'Timor-Leste', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'TON', 'Tonga', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'TUN', 'Tunisia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'TUR', 'Turkey', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'TUV', 'Tuvalu', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'TZA', 'Tanzania', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'UGA', 'Uganda', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'UKR', 'Ukraine', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'UZB', 'Uzbekistan', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'VCT', 'St. Vincent and the Grenadines', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'VEN', 'Venezuela, RB', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'VNM', 'Vietnam', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'VUT', 'Vanuatu', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'WSM', 'Samoa', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'XKX', 'Kosovo', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'YEM', 'Yemen, Rep.', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'ZAF', 'South Africa', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'ZMB', 'Zambia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('LMY', 'ZWE', 'Zimbabwe', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'ALB', 'Albania', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'ARG', 'Argentina', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'ARM', 'Armenia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'ASM', 'American Samoa', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'AZE', 'Azerbaijan', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'BGR', 'Bulgaria', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'BIH', 'Bosnia and Herzegovina', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'BLR', 'Belarus', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'BLZ', 'Belize', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'BRA', 'Brazil', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'BWA', 'Botswana', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'CHN', 'China', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'COL', 'Colombia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'CRI', 'Costa Rica', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'CUB', 'Cuba', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'DMA', 'Dominica', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'DOM', 'Dominican Republic', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'ECU', 'Ecuador', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'FJI', 'Fiji', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'GAB', 'Gabon', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'GEO', 'Georgia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'GNQ', 'Equatorial Guinea', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'GRD', 'Grenada', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'GTM', 'Guatemala', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'GUY', 'Guyana', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'IDN', 'Indonesia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'IRN', 'Iran, Islamic Rep.', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'IRQ', 'Iraq', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'JAM', 'Jamaica', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'JOR', 'Jordan', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'KAZ', 'Kazakhstan', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'LBN', 'Lebanon', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'LBY', 'Libya', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'LCA', 'St. Lucia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'MDV', 'Maldives', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'MEX', 'Mexico', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'MHL', 'Marshall Islands', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'MKD', 'North Macedonia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'MNE', 'Montenegro', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'MYS', 'Malaysia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'NAM', 'Namibia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'PER', 'Peru', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'PRY', 'Paraguay', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'RUS', 'Russian Federation', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'SRB', 'Serbia', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'SUR', 'Suriname', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'THA', 'Thailand', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'TKM', 'Turkmenistan', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'TON', 'Tonga', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'TUR', 'Turkey', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'TUV', 'Tuvalu', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'VCT', 'St. Vincent and the Grenadines', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'VEN', 'Venezuela, RB', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'WSM', 'Samoa', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'XKX', 'Kosovo', '2021');
INSERT IGNORE INTO ilga_income_worldbank (income_category, iso3, country, year) VALUES ('UMC', 'ZAF', 'South Africa', '2021');
